export const GET_CONTACTS = "GET_CONTACTS";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const FILTER_CONTACTS = "FILTER_CONTACTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CONTACT_ERROR = "CONTACT_ERROR";
export const GET_USERS = "GET_USERS";
export const GET_FRIENDS = "GET_FRIENDS";
export const GET_POSTS = "GET_POSTS";
export const GET_PENDING = "GET_PENDING";
export const REMOVE_FROM_PENDING = "REMOVE_FROM_PENDING";
export const ADD_TO_FRIEND_REQUEST_SUBMITTED = "ADD_TO_FRIEND_REQUEST_SUBMITTED";
export const GET_FRIEND_REQUEST_SUBMITTED = "GET_FRIEND_REQUEST_SUBMITTED";
export const EDIT_PROFILE_INFO = "EDIT_PROFILE_INFO";
export const GET_PROFILE_INFO = "GET_PROFILE_INFO";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const EDIT_BACKGROUND_PHOTO = "EDIT_BACKGROUND_PHOTO";
export const GET_BACKGROUND_PHOTO = "GET_BACKGROUND_PHOTO";
export const GET_PHOTOALBUM = "GET_PHOTOALBUM";
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_CURRENTUSER_COMMENTS = "GET_CURRENTUSER_COMMENTS";
export const USER_ERROR = "USER_ERROR";
export const EDIT_PROFILE_PIC = "EDIT_PROFILE_PIC";
export const GET_PROFILE_PHOTO = "GET_PROFILE_PHOTO";
export const ADD_COMMENT_LIKE = "ADD_COMMENT_LIKE";
export const CLEAR_USER_STATE = "CLEAR_USER_STATE";
export const CLEAR_PROFILE_STATE = "CLEAR_PROFILE_STATE";








